
contact_links:
  - name: Ask Questions
    url: https://github.com/asfadmin/Discovery-PytestAutomation/discussions
    about: Feel free to ask and answer questions in GitHub's Discussions

  - name: Gitter Chat
    url: https://gitter.im/ASFDiscovery/pytest-automation
    about: Come chat with the pytest-automation community
