name: Check for required labels

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled
      - synchronize
    branches:
      - stable

jobs:
  check-version-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'open'
    steps:
      - name: Require Version Label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch, skip-release"