# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]
    branches:
      - stable

jobs:

  DeployToPypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      ## TODO: Make the test suite
      # # Run the local test sutie action:
      # - uses: ./.github/actions/pytest-automation
      #   with:
      #     PYTEST_OPTIONS: -n auto

      # Actually push the package now:
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine packaging

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*